### ISSUE TITLE
Issue with installation  (ValueError: Cannot find the version number!)

### ISSUE THREAD

**Issue by HarinderUNAM** [sergiocallegari/PyDSM#8]
I am getting the following error while trying to install Pydsm on my ubuntu system:

/Downloads/PyDSM-master$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 41, in <module>
    __version__ = get_git_version(store="pydsm/RELEASE-VERSION")
  File "/home/harry/Downloads/PyDSM-master/setup_helper_version.py", line 96, in get_git_version
    raise ValueError("Cannot find the version number!")
ValueError: Cannot find the version number!

**Comment by sergiocallegari** [comment]
I strongly suspect that there are issues with PyDSM with current versions of python and the other software stacks PyDSM is relying upon. I'll try to look into the issue when my office reopens at the beginning of September and make an updated release if needed.

Thanks for reporting!

**Comment by HarinderUNAM** [comment]
Thanks for your prompt reply! Just for your information, I am using python 3.

**Comment by sergiocallegari** [comment]
Hi, there is now a new version of PyDSM that you may want to try. Please let me have your feedback on it.

**Comment by sergiocallegari** [comment]
Should now be fixed in the latest release
